candidate_dir: ${dataset.candidate_dir}
output_dir: ${run.iter_dir}/data/multitask
triplet_dir: ${preprocessing.triplet.output_dir}
binary_dir: ${preprocessing.binary.output_dir}
clf_dir: ${preprocessing.clf.output_dir}
ablation: false
n_train: 60000
n_dev: 10000
rnd_seed: ${run.rnd_seed}